services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    # not required to mount data to container to load it
    #volumes:
    #  - ./raw-data:/raw-data
